### ISSUE TITLE
Some links in README.md is not available

### ISSUE THREAD

**Issue by entalent** [hjjpku/Action_Detection_DQN#1]
Some links (for example, the link to processed dataset and pre-trained torch model) in README.md points to https://github.com/hjjpku/Action_Detection_DQN/blob/master, which returns 404. Could you please change these links to correct url or mention when the data will be available?

**Comment by hjjpku** [comment]
Oh, I am sorry for that.  Some other tasks mess me up these days and I will fix it as soon as possible. I will leave a message to you as long as I fix it up.

**Comment by hjjpku** [comment]
The link to  processed dataset and pre-trained torch model have been fixed. =)
